# Generated by Django 3.2.1 on 2023-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
