# Generated by Django 4.2 on 2023-06-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_todoitem_priority_remove_todoitem_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='previous',
        ),
    ]
