# Generated by Django 4.2 on 2023-06-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_todoitem_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistmap',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolistmap',
            name='name',
            field=models.CharField(default='test', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
