# Generated by Django 4.2 on 2023-06-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todolistmap_completed_todolistmap_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistmap',
            old_name='seq',
            new_name='normal',
        ),
        migrations.AlterField(
            model_name='todolistmap',
            name='completed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
