# Generated by Django 4.2 on 2023-06-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_seq_todolistmap_normal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistmap',
            old_name='normal',
            new_name='seq',
        ),
        migrations.AlterField(
            model_name='todolistmap',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolistmap',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
