# Generated by Django 4.2 on 2023-06-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_rename_normal_todolistmap_seq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistmap',
            name='completed',
        ),
    ]
