# Generated by Django 4.2 on 2023-06-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_todolistmap_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmap',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
