# Generated by Django 4.2 on 2023-06-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_todolistmap_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmap',
            name='seq',
            field=models.JSONField(default=list),
        ),
    ]
