# Generated by Django 4.2 on 2023-06-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_todoitem_todo_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='todo_list',
        ),
        migrations.RemoveField(
            model_name='todolistmap',
            name='name',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='child_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordering', to='todo.todolistmap'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='todo.todoitem'),
        ),
    ]
