# Generated by Django 4.2 on 2023-06-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_remove_todoitem_todo_list_remove_todolistmap_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='child_map',
        ),
        migrations.AddField(
            model_name='todolistmap',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_map', to='todo.todoitem'),
        ),
    ]
