# Generated by Django 4.2 on 2023-06-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_remove_todoitem_child_map_todolistmap_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolistmap',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_map', to='todo.todoitem'),
        ),
    ]
