# Generated by Django 4.2 on 2023-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_todoitem_favorite_alter_todolistmap_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
