# Generated by Django 4.2 on 2023-06-17 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0018_todoitem_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
